// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: helloworld/v1/{{cookiecutter.repo_name}}.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// {{cookiecutter.service_name}}Client is the client API for {{cookiecutter.service_name}} service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type {{cookiecutter.service_name}}Client interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type {{cookiecutter.repo_name}}Client struct {
	cc grpc.ClientConnInterface
}

func New{{cookiecutter.service_name}}Client(cc grpc.ClientConnInterface) {{cookiecutter.service_name}}Client {
	return &{{cookiecutter.repo_name}}Client{cc}
}

func (c *{{cookiecutter.repo_name}}Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.v1.{{cookiecutter.service_name}}/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// {{cookiecutter.service_name}}Server is the server API for {{cookiecutter.service_name}} service.
// All implementations must embed Unimplemented{{cookiecutter.service_name}}Server
// for forward compatibility
type {{cookiecutter.service_name}}Server interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplemented{{cookiecutter.service_name}}Server()
}

// Unimplemented{{cookiecutter.service_name}}Server must be embedded to have forward compatible implementations.
type Unimplemented{{cookiecutter.service_name}}Server struct {
}

func (Unimplemented{{cookiecutter.service_name}}Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (Unimplemented{{cookiecutter.service_name}}Server) mustEmbedUnimplemented{{cookiecutter.service_name}}Server() {}

// Unsafe{{cookiecutter.service_name}}Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to {{cookiecutter.service_name}}Server will
// result in compilation errors.
type Unsafe{{cookiecutter.service_name}}Server interface {
	mustEmbedUnimplemented{{cookiecutter.service_name}}Server()
}

func Register{{cookiecutter.service_name}}Server(s grpc.ServiceRegistrar, srv {{cookiecutter.service_name}}Server) {
	s.RegisterService(&{{cookiecutter.service_name}}_ServiceDesc, srv)
}

func _{{cookiecutter.service_name}}_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.({{cookiecutter.service_name}}Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.v1.{{cookiecutter.service_name}}/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.({{cookiecutter.service_name}}Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// {{cookiecutter.service_name}}_ServiceDesc is the grpc.ServiceDesc for {{cookiecutter.service_name}} service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var {{cookiecutter.service_name}}_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.{{cookiecutter.service_name}}",
	HandlerType: (*{{cookiecutter.service_name}}Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _{{cookiecutter.service_name}}_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/{{cookiecutter.repo_name}}.proto",
}
